# Generated by Django 4.2.19 on 2025-02-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='LOCK_REASON',
            field=models.CharField(blank=True, db_column='LOCK_REASON', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='PERMANENT_LOCK',
            field=models.BooleanField(db_column='PERMANENT_LOCK', default=False),
        ),
    ]
