# Generated by Django 4.2.19 on 2025-02-18 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_password_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='DATE_JOINED',
            field=models.DateTimeField(db_column='DATE_JOINED', default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='LAST_FAILED_LOGIN',
            field=models.DateTimeField(blank=True, db_column='LAST_FAILED_LOGIN', null=True),
        ),
    ]
