# Generated by Django 5.1.6 on 2025-02-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_customuser_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACADEMIC_YEAR',
            fields=[
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('DELETED_BY', models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True)),
                ('DELETED_AT', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('ACADEMIC_YEAR_ID', models.AutoField(db_column='ACADEMIC_YEAR_ID', primary_key=True, serialize=False)),
                ('START_DATE', models.DateField(db_column='START_DATE')),
                ('END_DATE', models.DateField(db_column='END_DATE')),
                ('INSTITUTE_CODE', models.CharField(db_column='INSTITUTE_CODE', max_length=50, unique=True)),
                ('IS_ACTIVE', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('CREATED_BY', models.CharField(db_column='CREATED_BY', default='system', max_length=50)),
                ('UPDATED_BY', models.CharField(db_column='UPDATED_BY', default='system', max_length=50)),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'db_table': 'ACADEMIC_YEARS',
            },
        ),
    ]
