# Generated by Django 5.1.6 on 2025-02-26 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_academic_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academic_year',
            name='INSTITUTE_CODE',
        ),
        migrations.AddField(
            model_name='academic_year',
            name='INSTITUTE',
            field=models.ForeignKey(db_column='INSTITUTE_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_years', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='academic_year',
            name='UNIVERSITY',
            field=models.ForeignKey(db_column='UNIVERSITY_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_years', to='accounts.university'),
        ),
    ]
