# Generated by Django 5.1.6 on 2025-03-04 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_department_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='DASHBOARD_MASTER',
            fields=[
                ('CREATED_BY', models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_BY', models.CharField(blank=True, db_column='UPDATED_BY', max_length=50, null=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('DELETED_BY', models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True)),
                ('DELETED_AT', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('DBM_ID', models.AutoField(db_column='DBM_ID', primary_key=True, serialize=False)),
                ('EMP_ID', models.CharField(db_column='EMP_ID', max_length=50, unique=True)),
                ('DASHBOARD_NAME', models.CharField(db_column='DASHBOARD_NAME', max_length=50)),
                ('INSTITUTE', models.ForeignKey(db_column='INSTITUTE_ID', on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_master', to='accounts.institute')),
            ],
            options={
                'verbose_name': 'Dashboard Master',
                'verbose_name_plural': 'Dashboard Master',
                'db_table': 'DASHBOARD_MASTER',
            },
        ),
    ]
