# Generated by Django 5.1.6 on 2025-02-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_academic_year_institute_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academic_year',
            name='UNIVERSITY',
        ),
        migrations.AddField(
            model_name='academic_year',
            name='ACADEMIC_YEAR',
            field=models.CharField(db_column='ACADEMIC_YEAR', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='academic_year',
            name='INSTITUTE',
            field=models.CharField(db_column='INSTITUTE', max_length=50, null=True),
        ),
    ]
