# Generated by Django 4.2.19 on 2025-03-04 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_department_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='INSTITUTE',
            field=models.ForeignKey(blank=True, db_column='INSTITUTE_ID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='accounts.institute'),
        ),
    ]
