# Generated by Django 5.1.6 on 2025-03-04 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_department_is_active'),
        ('accounts', '0013_remove_academic_year_university_and_more'),
    ]

    operations = [
    ]
