# Generated by Django 5.1.6 on 2025-03-04 08:57

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_dashboard_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard_master',
            name='INSTITUTE',
            field=models.CharField(db_column='INSTITUTE_ID', verbose_name=accounts.models.INSTITUTE),
        ),
    ]
