# Generated by Django 4.2.19 on 2025-03-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_department_institute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='INSTITUTE',
        ),
        migrations.AddField(
            model_name='department',
            name='INSTITUTE_CODE',
            field=models.CharField(blank=True, db_column='INSTITUTE_CODE', default='DEFAULT', max_length=50, null=True),
        ),
    ]
