# Generated by Django 5.1.6 on 2025-03-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_20250304_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEMESTER_DURATION',
            fields=[
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('DELETED_BY', models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True)),
                ('DELETED_AT', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('SEMESTER_DURATION_ID', models.AutoField(db_column='SEMESTER_DURATION_ID', primary_key=True, serialize=False)),
                ('SEMESTER', models.CharField(db_column='SEMESTER', max_length=50, null=True)),
                ('START_DATE', models.DateField(db_column='START_DATE')),
                ('END_DATE', models.DateField(db_column='END_DATE')),
                ('IS_ACTIVE', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('CREATED_BY', models.CharField(db_column='CREATED_BY', default='system', max_length=50)),
                ('UPDATED_BY', models.CharField(db_column='UPDATED_BY', default='system', max_length=50)),
            ],
            options={
                'verbose_name': 'Semester Duration',
                'verbose_name_plural': 'Semester Durations',
                'db_table': 'SEMESTER_DURATION',
            },
        ),
    ]
