# Generated by Django 5.1.6 on 2025-03-10 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_department_institute_and_more'),
        ('accounts', '0015_semester_duration'),
    ]

    operations = [
    ]
