# Generated by Django 4.2.19 on 2025-03-08 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_department_institute_and_more'),
        ('accounts', '0015_semester_duration'),
    ]

    operations = [
    ]
