# Generated by Django 4.2.19 on 2025-03-12 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_dashboard_master_institute'),
        ('accounts', '0016_merge_20250308_1504'),
        ('accounts', '0016_merge_20250310_1335'),
    ]

    operations = [
    ]
