# Generated by Django 4.2.19 on 2025-03-12 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_merge_20250312_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='STUDENT_MASTER',
            fields=[
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('DELETED_BY', models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True)),
                ('DELETED_AT', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('STUDENT_MASTER_ID', models.AutoField(db_column='STUDENT_MASTER_ID', primary_key=True, serialize=False)),
                ('FULL_NAME', models.CharField(db_column='FULL_NAME', default='Unknown Student', max_length=255)),
                ('CONTACT_NUMBER', models.CharField(blank=True, db_column='CONTACT_NUMBER', max_length=15, null=True)),
                ('EMAIL', models.EmailField(db_column='EMAIL', max_length=254, unique=True)),
                ('ADDRESS', models.TextField(blank=True, db_column='ADDRESS', null=True)),
                ('IS_ACTIVE', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('CREATED_BY', models.CharField(db_column='CREATED_BY', default='system', max_length=50)),
                ('UPDATED_BY', models.CharField(db_column='UPDATED_BY', default='system', max_length=50)),
            ],
            options={
                'verbose_name': 'Student Master',
                'verbose_name_plural': 'Student Masters',
                'db_table': '"ADMIN"."STUDENT_MASTER"',
            },
        ),
    ]
