# Generated by Django 4.2.19 on 2025-03-15 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_admission_quota_master_caste_master_quota_master_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADMISSION_QUOTA_MASTER',
            fields=[
                ('CREATED_BY', models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_BY', models.CharField(blank=True, db_column='UPDATED_BY', max_length=50, null=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('DELETED_BY', models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True)),
                ('DELETED_AT', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('ADMN_QUOTA_ID', models.AutoField(db_column='ADMN_QUOTA_ID', primary_key=True, serialize=False)),
                ('NAME', models.CharField(db_column='NAME', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Admission Quota Master',
                'verbose_name_plural': 'Admission Quota Masters',
                'db_table': 'ADMISSION_QUOTA_MASTER',
            },
        ),
        migrations.CreateModel(
            name='CASTE_MASTER',
            fields=[
                ('CREATED_BY', models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_BY', models.CharField(blank=True, db_column='UPDATED_BY', max_length=50, null=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('DELETED_BY', models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True)),
                ('DELETED_AT', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('CASTE_ID', models.AutoField(db_column='CASTE_ID', primary_key=True, serialize=False)),
                ('NAME', models.CharField(db_column='NAME', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Caste Master',
                'verbose_name_plural': 'Caste Masters',
                'db_table': 'CASTE_MASTER',
            },
        ),
        migrations.CreateModel(
            name='QUOTA_MASTER',
            fields=[
                ('CREATED_BY', models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_BY', models.CharField(blank=True, db_column='UPDATED_BY', max_length=50, null=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('DELETED_BY', models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True)),
                ('DELETED_AT', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('QUOTA_ID', models.AutoField(db_column='QUOTA_ID', primary_key=True, serialize=False)),
                ('NAME', models.CharField(db_column='NAME', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Quota Master',
                'verbose_name_plural': 'Quota Masters',
                'db_table': 'QUOTA_MASTER',
            },
        ),
        migrations.AlterModelOptions(
            name='dashboard_master',
            options={'verbose_name': 'Dashboard Master', 'verbose_name_plural': 'Dashboard Masters'},
        ),
        migrations.AlterField(
            model_name='dashboard_master',
            name='INSTITUTE',
            field=models.CharField(db_column='INSTITUTE_ID', max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='INSTITUTE_CODE',
            field=models.CharField(db_column='INSTITUTE_CODE', default='DEFAULT', max_length=50),
        ),
        migrations.CreateModel(
            name='YEAR',
            fields=[
                ('CREATED_BY', models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_BY', models.CharField(blank=True, db_column='UPDATED_BY', max_length=50, null=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('DELETED_BY', models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True)),
                ('DELETED_AT', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('YEAR_ID', models.AutoField(db_column='YEAR_ID', primary_key=True, serialize=False)),
                ('YEAR', models.CharField(db_column='YEAR', max_length=255)),
                ('BRANCH', models.ForeignKey(db_column='BRANCH_ID', on_delete=django.db.models.deletion.PROTECT, related_name='years', to='accounts.branch')),
            ],
            options={
                'verbose_name': 'Year',
                'verbose_name_plural': 'Years',
                'db_table': 'YEARS',
            },
        ),
        migrations.CreateModel(
            name='SEMESTER',
            fields=[
                ('CREATED_BY', models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_BY', models.CharField(blank=True, db_column='UPDATED_BY', max_length=50, null=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('DELETED_BY', models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True)),
                ('DELETED_AT', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('SEMESTER_ID', models.AutoField(db_column='SEMESTER_ID', primary_key=True, serialize=False)),
                ('SEMESTER', models.CharField(db_column='SEMESTER', max_length=255)),
                ('YEAR', models.ForeignKey(db_column='YEAR_ID', on_delete=django.db.models.deletion.PROTECT, related_name='semesters', to='accounts.year')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'db_table': 'SEMESTERS',
            },
        ),
    ]
