# Generated by Django 5.1.6 on 2025-03-13 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_admission_quota_master_caste_master_quota_master_and_more'),
    ]

    operations = [
        
    ]
