# Generated by Django 5.1.6 on 2025-03-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_admission_quota_master_caste_master_quota_master_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard_master',
            name='EMP_ID',
            field=models.CharField(db_column='EMP_ID', max_length=50),
        ),
    ]
