# Generated by Django 4.2.19 on 2025-03-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_admission_quota_master_caste_master_quota_master_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='STUDENT_MASTER',
        ),
        migrations.AlterField(
            model_name='dashboard_master',
            name='EMP_ID',
            field=models.CharField(db_column='EMP_ID', max_length=50),
        ),
    ]
