# Generated by Django 4.2.7 on 2025-03-23 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_alter_dashboard_master_emp_id"),
        ("accounts", "0020_delete_student_master_alter_dashboard_master_emp_id"),
    ]

    operations = []
