# Generated by Django 5.1.6 on 2025-04-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_merge_20250323_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHECK_LIST_DOCUMENTS',
            fields=[
                ('CREATED_BY', models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_BY', models.CharField(blank=True, db_column='UPDATED_BY', max_length=50, null=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('DELETED_BY', models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True)),
                ('DELETED_AT', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('RECORD_ID', models.AutoField(db_column='RECORD_ID', primary_key=True, serialize=False)),
                ('NAME', models.CharField(db_column='NAME', max_length=50, null=True)),
                ('IS_MANDATORY', models.BooleanField(db_column='IS_MANDATORY', default=True)),
            ],
            options={
                'verbose_name': 'Check List Documents',
                'verbose_name_plural': 'Check List Documents',
                'db_table': 'CHECK_LIST_DOCUMNETS',
            },
        ),
    ]
