# Generated by Django 5.1.6 on 2025-04-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_check_list_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_list_documents',
            name='IS_MANDATORY',
            field=models.BooleanField(db_column='IS_MANDATORY', default=False),
        ),
    ]
