# Generated by Django 5.1.6 on 2025-05-05 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_check_list_documents_is_mandatory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CHECK_LIST_DOCUMENTS',
        ),
    ]
