# Generated by Django 4.2.19 on 2025-02-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='USER',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('FIRST_NAME', models.CharField(max_length=100)),
                ('LAST_NAME', models.CharField(max_length=100)),
                ('USER_ID', models.CharField(max_length=50, unique=True)),
                ('EMAIL_ID', models.EmailField(max_length=255, unique=True)),
                ('USER_TYPE', models.CharField(choices=[('SUPER_ADMIN', 'SUPER_ADMIN'), ('INSTITUTE_ADMIN', 'INSTITUTE_ADMIN'), ('HOD', 'HOD'), ('PROFESSOR', 'PROFESSOR'), ('ASSISTANT_PROFESSOR', 'ASSISTANT_PROFESSOR'), ('TEACHER', 'TEACHER'), ('STUDENT', 'STUDENT'), ('LIBRARIAN', 'LIBRARIAN'), ('ACCOUNTANT', 'ACCOUNTANT'), ('FEES_COLLECTOR', 'FEES_COLLECTOR'), ('CLERK', 'CLERK'), ('ADMISSION_STAFF', 'ADMISSION_STAFF'), ('EXAMINATION_STAFF', 'EXAMINATION_STAFF')], default='STUDENT', max_length=50)),
                ('LAST_LOGIN', models.DateTimeField(blank=True, null=True)),
                ('LAST_LOGIN_IP', models.CharField(blank=True, max_length=45, null=True)),
                ('USER_PREFIX', models.CharField(blank=True, max_length=2, null=True)),
                ('USER_YEAR', models.IntegerField(blank=True, null=True)),
                ('USER_TYPE_CODE', models.CharField(blank=True, max_length=1, null=True)),
                ('USER_NUMBER', models.IntegerField(blank=True, null=True)),
                ('IS_ACTIVE', models.BooleanField(default=True)),
                ('IS_STAFF', models.BooleanField(default=False)),
                ('IS_SUPERUSER', models.BooleanField(default=False)),
                ('CREATED_BY', models.BigIntegerField(blank=True, null=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('UPDATED_BY', models.BigIntegerField(blank=True, null=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('DELETED_BY', models.BigIntegerField(blank=True, null=True)),
                ('DELETED_AT', models.DateTimeField(blank=True, null=True)),
                ('IS_DELETED', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'USERS',
                'indexes': [models.Index(fields=['USER_PREFIX', 'USER_YEAR', 'USER_TYPE_CODE', 'USER_NUMBER'], name='USERS_USER_PR_062ebc_idx')],
            },
        ),
    ]
