CREATE SCHEMA IF NOT EXISTS "ACADEMIC";
CREATE SCHEMA IF NOT EXISTS "ADMIN";
CREATE SCHEMA IF NOT EXISTS "ESTABLISHMENT";
CREATE SCHEMA IF NOT EXISTS "FACULTY";
CREATE SCHEMA IF NOT EXISTS "STUDENT";
