# Generated by Django 5.1.7 on 2025-04-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COLLEGE_EXAM_TYPE',
            fields=[
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('DELETED_BY', models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True)),
                ('DELETED_AT', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('RECORD_ID', models.AutoField(db_column='RECORD_ID', primary_key=True, serialize=False)),
                ('ACADEMIC_YEAR', models.CharField(db_column='ACADEMIC_YEAR', max_length=10)),
                ('PROGRAM_ID', models.IntegerField(db_column='PROGRAM_ID')),
                ('EXAM_TYPE', models.CharField(db_column='EXAM_TYPE', max_length=50)),
                ('IS_ACTIVE', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('CREATED_BY', models.CharField(db_column='CREATED_BY', default='system', max_length=50)),
                ('UPDATED_BY', models.CharField(db_column='UPDATED_BY', default='system', max_length=50)),
            ],
            options={
                'verbose_name': 'College Exam Type',
                'verbose_name_plural': 'College Exam Types',
                'db_table': '"EXAM"."COLLEGE_EXAM_TYPE"',
            },
        ),
    ]
