# Generated by Django 4.2.19 on 2025-02-28 11:44

from django.db import migrations, models
import establishments.models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0004_employee_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_master',
            name='PROFILE_IMAGE',
            field=models.ImageField(blank=True, db_column='PROFILE_IMAGE', null=True, upload_to=establishments.models.employee_profile_path),
        ),
    ]
