# Generated by Django 4.2.19 on 2025-02-28 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0005_alter_employee_master_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_master',
            name='UNIVERSITY',
        ),
    ]
