# Generated by Django 4.2.19 on 2025-02-28 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_department_is_active'),
        ('establishments', '0006_remove_employee_master_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_master',
            name='CATEGORY',
            field=models.ForeignKey(blank=True, db_column='CATEGORY_ID', null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.category'),
        ),
        migrations.AlterField(
            model_name='employee_master',
            name='DATE_OF_BIRTH',
            field=models.DateField(blank=True, db_column='DATE_OF_BIRTH', null=True),
        ),
        migrations.AlterField(
            model_name='employee_master',
            name='EMP_TYPE',
            field=models.ForeignKey(blank=True, db_column='EMP_TYPE_ID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees_type', to='establishments.type_master'),
        ),
        migrations.AlterField(
            model_name='employee_master',
            name='MARITAL_STATUS',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('other', 'Other')], db_column='MARITAL_STATUS', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee_master',
            name='PERMANENT_ADDRESS',
            field=models.TextField(blank=True, db_column='PERMANENT_ADDRESS', null=True),
        ),
        migrations.AlterField(
            model_name='employee_master',
            name='PERMANENT_CITY',
            field=models.CharField(blank=True, db_column='PERMANENT_CITY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee_master',
            name='PERMANENT_PIN',
            field=models.CharField(blank=True, db_column='PERMANENT_PIN', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='employee_master',
            name='POSITION',
            field=models.CharField(blank=True, db_column='POSITION', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee_master',
            name='SHIFT',
            field=models.ForeignKey(blank=True, db_column='SHIFT', null=True, on_delete=django.db.models.deletion.PROTECT, to='establishments.shift_master'),
        ),
        migrations.AlterField(
            model_name='employee_master',
            name='STATUS',
            field=models.ForeignKey(blank=True, db_column='STATUS_ID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees_status', to='establishments.status_master'),
        ),
    ]
