# Generated by Django 5.1.6 on 2025-03-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_master',
            name='ACTIVE',
            field=models.CharField(db_column='ACTIVE', default=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='ADMISSION_DATE',
            field=models.DateField(blank=True, db_column='ADMISSION_DATE', null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='ADMN_ROUND',
            field=models.CharField(blank=True, db_column='ADMN_ROUND', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='BANK_ACC_NO',
            field=models.CharField(blank=True, db_column='BANK_ACC_NO', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='BANK_NAME',
            field=models.CharField(blank=True, db_column='BANK_NAME', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='BLOOD_GR',
            field=models.CharField(blank=True, db_column='BLOOD_GR', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='CASTE',
            field=models.CharField(blank=True, db_column='CASTE', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='DATEOFEDIT',
            field=models.DateField(auto_now=True, db_column='DATEOFEDIT', null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='DATEOFENTRY',
            field=models.DateField(auto_now_add=True, db_column='DATEOFENTRY', null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='DOB_WORD',
            field=models.CharField(blank=True, db_column='DOB_WORD', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='EDITPERSON',
            field=models.CharField(blank=True, db_column='EDITPERSON', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='EMERGENCY_NO',
            field=models.CharField(blank=True, db_column='EMERGENCY_NO', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='ENROLMENT_NO',
            field=models.CharField(blank=True, db_column='ENROLMENT_NO', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='ENTRYPERSON',
            field=models.CharField(blank=True, db_column='ENTRYPERSON', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='HANDICAPPED',
            field=models.CharField(db_column='HANDICAPPED', default=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='JOINING_STATUS',
            field=models.CharField(blank=True, db_column='JOINING_STATUS', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='JOINING_STATUS_DATE',
            field=models.DateField(blank=True, db_column='JOINING_STATUS_DATE', null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='LATERAL_STATUS',
            field=models.CharField(blank=True, db_column='LATERAL_STATUS', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='LOC_ADDRESS',
            field=models.TextField(blank=True, db_column='LOC_ADDRESS', null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='LOC_CITY',
            field=models.CharField(blank=True, db_column='LOC_CITY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='LOC_DIST',
            field=models.CharField(blank=True, db_column='LOC_DIST', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='LOC_PHONE_NO',
            field=models.CharField(blank=True, db_column='LOC_PHONE_NO', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='LOC_PIN',
            field=models.CharField(blank=True, db_column='LOC_PIN', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='LOC_STATE_ID',
            field=models.IntegerField(db_column='LOC_STATE_ID', default=0),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='LOC_TALUKA',
            field=models.CharField(blank=True, db_column='LOC_TALUKA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='MARK_ID',
            field=models.CharField(blank=True, db_column='MARK_ID', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='MOTHER_NAME',
            field=models.CharField(blank=True, db_column='MOTHER_NAME', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='NATIONALITY',
            field=models.CharField(blank=True, db_column='NATIONALITY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='PARENT_NAME',
            field=models.CharField(blank=True, db_column='PARENT_NAME', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='PER_ADDRESS',
            field=models.TextField(blank=True, db_column='PER_ADDRESS', null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='PER_CITY',
            field=models.CharField(blank=True, db_column='PER_CITY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='PER_DIST',
            field=models.CharField(blank=True, db_column='PER_DIST', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='PER_PHONE_NO',
            field=models.CharField(blank=True, db_column='PER_PHONE_NO', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='PER_PIN',
            field=models.CharField(blank=True, db_column='PER_PIN', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='PER_STATE_ID',
            field=models.IntegerField(db_column='PER_STATE_ID', default=0),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='PER_TALUKA',
            field=models.CharField(blank=True, db_column='PER_TALUKA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='REGISTRATION_DATE',
            field=models.DateField(blank=True, db_column='REGISTRATION_DATE', null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='RELIGION',
            field=models.CharField(blank=True, db_column='RELIGION', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='RETENTION_STATUS_DATE',
            field=models.DateField(blank=True, db_column='RETENTION_STATUS_DATE', null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='STATUS',
            field=models.CharField(blank=True, db_column='STATUS', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='VALIDITY',
            field=models.DateField(blank=True, db_column='VALIDITY', null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='YEAR_SEM_ID',
            field=models.IntegerField(db_column='YEAR_SEM_ID', default=0),
        ),
    ]
