# Generated by Django 5.1.6 on 2025-04-03 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_result_grade_points_student_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='STUDENT_DETAILS',
            fields=[
                ('CREATED_BY', models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True)),
                ('UPDATED_BY', models.CharField(blank=True, db_column='UPDATED_BY', max_length=50, null=True)),
                ('DELETED_BY', models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True)),
                ('DELETED_AT', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('RECORD_ID', models.AutoField(db_column='RECORD_ID', primary_key=True, serialize=False)),
                ('PLACE_OF_BIRTH', models.CharField(blank=True, db_column='PLACE_OF_BIRTH', default='', max_length=100)),
                ('LAST_CLG_ATTEND', models.CharField(blank=True, db_column='LAST_CLG_ATTEND', default='', max_length=255)),
                ('LAST_CLG_ADD', models.CharField(blank=True, db_column='LAST_CLG_ADD', default='')),
                ('LAST_CLG_CITY', models.CharField(blank=True, db_column='LAST_CLG_CITY', default='', max_length=100)),
                ('LAST_CLG_UNIV', models.CharField(blank=True, db_column='LAST_CLG_UNIV', default='', max_length=255)),
                ('LAST_CLG_ROLL', models.CharField(blank=True, db_column='LAST_CLG_ROLL', default='', max_length=50)),
                ('PCM_MARKS', models.DecimalField(blank=True, db_column='PCM_MARKS', decimal_places=2, max_digits=6, null=True)),
                ('PCM_OUTOF', models.DecimalField(blank=True, db_column='PCM_OUTOF', decimal_places=2, max_digits=6, null=True)),
                ('TOT_MARKS_OBTAIN', models.DecimalField(blank=True, db_column='TOT_MARKS_OBTAIN', decimal_places=2, max_digits=6, null=True)),
                ('TOT_MAX_MARKS', models.DecimalField(blank=True, db_column='TOT_MAX_MARKS', decimal_places=2, max_digits=6, null=True)),
                ('SCORE', models.DecimalField(blank=True, db_column='SCORE', decimal_places=2, max_digits=6, null=True)),
                ('MERIT', models.DecimalField(blank=True, db_column='MERIT', decimal_places=2, max_digits=6, null=True)),
                ('NATIONALITY', models.CharField(db_column='NATIONALITY', default='INDIAN', max_length=50)),
                ('DOMICILE_ID', models.IntegerField(blank=True, db_column='DOMICILE_ID', default='', max_length=50)),
                ('ADMISSION_QUOTA', models.IntegerField(blank=True, db_column='ADMISSION_QUOTA', default='', max_length=50)),
                ('QUALIFYING_EXAM', models.CharField(blank=True, db_column='QUALIFYING_EXAM', default='', max_length=100)),
                ('MONTH_OF_PASSING', models.CharField(blank=True, db_column='MONTH_OF_PASSING', default='', max_length=20)),
                ('YEAR_OF_PASSING', models.IntegerField(blank=True, db_column='YEAR_OF_PASSING', null=True)),
                ('MEDIUM', models.CharField(blank=True, db_column='MEDIUM', default='', max_length=50)),
                ('DRV_LICENSE', models.CharField(blank=True, db_column='DRV_LICENSE', default='', max_length=20)),
                ('AADHAR_NO', models.CharField(blank=True, db_column='AADHAR_NO', default='', max_length=12)),
                ('BANK_NAME', models.CharField(blank=True, db_column='BANK_NAME', default='', max_length=100)),
                ('BRANCH_NAME', models.CharField(blank=True, db_column='BRANCH_NAME', default='', max_length=100)),
                ('BANK_ACCOUNT_NO', models.CharField(blank=True, db_column='BANK_ACCOUNT_NO', default='', max_length=20)),
                ('BANK_CITY', models.CharField(blank=True, db_column='BANK_CITY', default='', max_length=100)),
                ('MINORITY', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], db_column='MINORITY', default='NO', max_length=3)),
                ('HOSTELER', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], db_column='HOSTELER', default='NO', max_length=3)),
                ('MOTHER_MOB', models.CharField(blank=True, db_column='MOTHER_MOB', default='', max_length=15)),
                ('PARENT_MAIL', models.EmailField(blank=True, db_column='PARENT_MAIL', default='', max_length=254)),
                ('FATHER_MOB', models.CharField(blank=True, db_column='FATHER_MOB', default='', max_length=15)),
                ('INCOME', models.DecimalField(blank=True, db_column='INCOME', decimal_places=2, max_digits=10, null=True)),
                ('PAN_NO', models.CharField(blank=True, db_column='PAN_NO', default='', max_length=10)),
                ('COLLEGE_PREFERENCE', models.TextField(blank=True, db_column='COLLEGE_PREFERENCE', default='')),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('STUDENT_ID', models.OneToOneField(db_column='STUDENT_ID', on_delete=django.db.models.deletion.CASCADE, to='student.student_master')),
            ],
            options={
                'verbose_name': 'Student Details',
                'verbose_name_plural': 'Student Details',
                'db_table': '"STUDENT"."STUDENT_DETAILS"',
                'indexes': [models.Index(fields=['STUDENT_ID'], name='STUDENT_DET_STUDENT_0637df_idx'), models.Index(fields=['AADHAR_NO'], name='STUDENT_DET_AADHAR__f4505f_idx'), models.Index(fields=['PAN_NO'], name='STUDENT_DET_PAN_NO_6d1097_idx')],
            },
        ),
    ]
