# Generated by Django 5.1.6 on 2025-04-03 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_academic_term_created_by_and_more'),
        ('accounts', '0021_merge_20250323_2107'),
        ('student', '0003_alter_student_result_grade_points_student_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='STUDENT_ROLL_NUMBER_DETAILS',
            fields=[
                ('CREATED_BY', models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_BY', models.CharField(blank=True, db_column='UPDATED_BY', max_length=50, null=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('DELETED_BY', models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True)),
                ('DELETED_AT', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('RECORD_ID', models.AutoField(db_column='RECORD_ID', primary_key=True, serialize=False)),
                ('ROLL_NO', models.CharField(db_column='ROLLNO', max_length=20)),
                ('ACADEMIC_YEAR', models.ForeignKey(db_column='ACADEMIC_YEAR_ID', on_delete=django.db.models.deletion.PROTECT, to='academic.academic_year')),
                ('BRANCH', models.ForeignKey(db_column='BRANCH_ID', on_delete=django.db.models.deletion.PROTECT, to='accounts.branch')),
                ('INSTITUTE', models.ForeignKey(db_column='INSTITUTE_ID', on_delete=django.db.models.deletion.PROTECT, to='accounts.institute')),
                ('PROGRAM', models.ForeignKey(db_column='PROGRAM_ID', on_delete=django.db.models.deletion.PROTECT, to='accounts.program')),
                ('SEMESTER', models.ForeignKey(db_column='SEMESTER_ID', on_delete=django.db.models.deletion.PROTECT, to='accounts.semester')),
                ('STUDENT', models.ForeignKey(db_column='STUDENT_ID', on_delete=django.db.models.deletion.PROTECT, to='student.student')),
                ('YEAR', models.ForeignKey(db_column='YEAR_ID', on_delete=django.db.models.deletion.PROTECT, to='accounts.year')),
            ],
            options={
                'verbose_name': 'Student Roll Number Details',
                'verbose_name_plural': 'Student Roll Number Details',
                'db_table': '"STUDENT"."STUDENT_ROLL_NUMBER_DETAILS"',
            },
        ),
    ]
