# Generated by Django 5.1.6 on 2025-04-07 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_roll_number_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_roll_number_details',
            name='PROGRAM',
        ),
    ]
