# Generated by Django 4.2.7 on 2025-03-23 21:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_alter_student_master_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student_master",
            name="DATEOFEDIT",
        ),
        migrations.RemoveField(
            model_name="student_master",
            name="DATEOFENTRY",
        ),
        migrations.RemoveField(
            model_name="student_master",
            name="ENTRYPERSON",
        ),
        migrations.AlterField(
            model_name="student_master",
            name="ADMISSION_DATE",
            field=models.DateField(
                db_column="ADMISSION_DATE", default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="ADMN_ROUND",
            field=models.CharField(db_column="ADMN_ROUND", default="1", max_length=10),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="BANK_ACC_NO",
            field=models.CharField(
                blank=True, db_column="BANK_ACC_NO", default="", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="BANK_NAME",
            field=models.CharField(
                blank=True, db_column="BANK_NAME", default="", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="BATCH",
            field=models.CharField(
                db_column="BATCH",
                help_text="Expected graduation/passout year (e.g., 2025)",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="BLOOD_GR",
            field=models.CharField(db_column="BLOOD_GR", default="O+", max_length=5),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="CASTE",
            field=models.CharField(db_column="CASTE", default="GENERAL", max_length=50),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="DOB_WORD",
            field=models.CharField(
                blank=True, db_column="DOB_WORD", default="", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="EDITPERSON",
            field=models.CharField(
                db_column="EDITPERSON", default="SYSTEM", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="EMERGENCY_NO",
            field=models.CharField(
                blank=True, db_column="EMERGENCY_NO", default="", max_length=15
            ),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="ENROLMENT_NO",
            field=models.CharField(
                blank=True, db_column="ENROLMENT_NO", default="", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="FATHER_NAME",
            field=models.CharField(db_column="FATHER_NAME", default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="HANDICAPPED",
            field=models.CharField(
                db_column="HANDICAPPED", default="NO", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="IS_ACTIVE",
            field=models.CharField(db_column="IS_ACTIVE", default="YES", max_length=8),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="JOINING_STATUS",
            field=models.CharField(
                db_column="JOINING_STATUS", default="JOINED", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="JOINING_STATUS_DATE",
            field=models.DateField(
                db_column="JOINING_STATUS_DATE", default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="LATERAL_STATUS",
            field=models.CharField(
                db_column="LATERAL_STATUS", default="NO", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="LOC_ADDRESS",
            field=models.TextField(blank=True, db_column="LOC_ADDRESS", default=""),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="LOC_CITY",
            field=models.CharField(
                blank=True, db_column="LOC_CITY", default="", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="LOC_DIST",
            field=models.CharField(
                blank=True, db_column="LOC_DIST", default="", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="LOC_PHONE_NO",
            field=models.CharField(
                blank=True, db_column="LOC_PHONE_NO", default="", max_length=15
            ),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="LOC_PIN",
            field=models.CharField(
                blank=True, db_column="LOC_PIN", default="", max_length=6
            ),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="LOC_STATE_ID",
            field=models.IntegerField(db_column="LOC_STATE_ID", default=1),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="LOC_TALUKA",
            field=models.CharField(
                blank=True, db_column="LOC_TALUKA", default="", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="MARK_ID",
            field=models.CharField(
                blank=True, db_column="MARK_ID", default="0", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="MOTHER_NAME",
            field=models.CharField(
                blank=True, db_column="MOTHER_NAME", default="", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="NAME_ON_CERTIFICATE",
            field=models.CharField(
                blank=True, db_column="NAME_ON_CERTIFICATE", default="", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="NATIONALITY",
            field=models.CharField(
                db_column="NATIONALITY", default="INDIAN", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="PARENT_NAME",
            field=models.CharField(db_column="PARENT_NAME", default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="PER_ADDRESS",
            field=models.TextField(blank=True, db_column="PER_ADDRESS", default=""),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="PER_CITY",
            field=models.CharField(
                blank=True, db_column="PER_CITY", default="", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="PER_DIST",
            field=models.CharField(
                blank=True, db_column="PER_DIST", default="", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="PER_PHONE_NO",
            field=models.CharField(
                blank=True, db_column="PER_PHONE_NO", default="", max_length=15
            ),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="PER_PIN",
            field=models.CharField(
                blank=True, db_column="PER_PIN", default="", max_length=6
            ),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="PER_STATE_ID",
            field=models.IntegerField(db_column="PER_STATE_ID", default=1),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="PER_TALUKA",
            field=models.CharField(
                blank=True, db_column="PER_TALUKA", default="", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="QUOTA_ID",
            field=models.IntegerField(db_column="QUOTA_ID", default=1),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="REGISTRATION_DATE",
            field=models.DateField(
                db_column="REGISTRATION_DATE", default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="RELIGION",
            field=models.CharField(
                blank=True, db_column="RELIGION", default="", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="RETENTION_STATUS_DATE",
            field=models.DateField(
                db_column="RETENTION_STATUS_DATE", default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="STATUS",
            field=models.CharField(db_column="STATUS", default="ACTIVE", max_length=20),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="VALIDITY",
            field=models.DateField(
                db_column="VALIDITY", default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="student_master",
            name="YEAR_SEM_ID",
            field=models.IntegerField(db_column="YEAR_SEM_ID", default=1),
        ),
        migrations.AlterField(
            model_name="student_result",
            name="GRADE_POINTS",
            field=models.DecimalField(
                db_column="GRADE_POINTS", decimal_places=1, max_digits=10
            ),
        ),
    ]
