# Generated by Django 5.1.6 on 2025-04-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='DOMICILE_ID',
            field=models.IntegerField(blank=True, db_column='DOMICILE_ID', default='', max_length=50, null=True),
        ),
    ]
