# Generated by Django 5.1.6 on 2025-04-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_details_domicile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='DOMICILE_ID',
        ),
        migrations.AlterField(
            model_name='student_details',
            name='ADMISSION_QUOTA',
            field=models.IntegerField(blank=True, db_column='ADMISSION_QUOTA', default=''),
        ),
    ]
