# Generated by Django 5.1.6 on 2025-04-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_student_details_domicile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='ADMISSION_QUOTA',
            field=models.IntegerField(blank=True, db_column='ADMISSION_QUOTA', default='', null=True),
        ),
    ]
