# Generated by Django 5.1.6 on 2025-04-04 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_student_details_aadhar_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='STUDENT_ID',
            field=models.OneToOneField(db_column='STUDENT_ID', on_delete=django.db.models.deletion.CASCADE, to='student.student_master', to_field='STUDENT_ID'),
        ),
    ]
