# Generated by Django 5.1.6 on 2025-04-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_student_details_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='STUDENT_ACADEMIC_RECORD',
            fields=[
                ('CREATED_BY', models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_BY', models.CharField(blank=True, db_column='UPDATED_BY', max_length=50, null=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('DELETED_BY', models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True)),
                ('DELETED_AT', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('RECORD_ID', models.AutoField(db_column='RECORD_ID', primary_key=True, serialize=False)),
                ('STUDENT_ID', models.CharField(db_column='STUDENT_ID', max_length=20)),
                ('INSTITUTE_ID', models.CharField(db_column='INSTITUTE_ID', max_length=20)),
                ('CATEGORY', models.IntegerField(db_column='CATEGORY')),
                ('BATCH', models.CharField(db_column='BATCH', max_length=4)),
                ('ACADEMIC_YEAR', models.CharField(db_column='ACADEMIC_YEAR', max_length=10)),
                ('CLASS_YEAR', models.IntegerField(db_column='CLASS_YEAR')),
                ('ADMISSION_DATE', models.DateField(db_column='ADMISSION_DATE')),
                ('FORM_NO', models.IntegerField(db_column='FORM_NO')),
                ('QUOTA_ID', models.IntegerField(db_column='QUOTA_ID')),
                ('STATUS', models.CharField(db_column='STATUS', default='ACTIVE', max_length=20)),
                ('FEE_CATEGORY_ID', models.IntegerField(db_column='FEE_CATEGORY_ID')),
            ],
            options={
                'verbose_name': 'Student Academic Record',
                'verbose_name_plural': 'Student Academic Records',
                'db_table': '"STUDENT"."STUDENT_ACADEMIC_RECORD"',
            },
        ),
    ]
