# Generated by Django 5.1.6 on 2025-04-08 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_check_list_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_list_documents',
            name='NAME',
            field=models.CharField(db_column='NAME', max_length=1000, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='STUDENT_DOCUMENTS',
            fields=[
                ('CREATED_BY', models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_BY', models.CharField(blank=True, db_column='UPDATED_BY', max_length=50, null=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('DELETED_BY', models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True)),
                ('DELETED_AT', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('RECORDID', models.AutoField(primary_key=True, serialize=False)),
                ('ACADEMIC_YEAR', models.CharField(db_column='ACADEMIC_YEAR', max_length=10, null=True)),
                ('TEMPRETURN', models.CharField(blank=True, db_column='TEMPRETURN', max_length=1, null=True)),
                ('RETURN', models.CharField(blank=True, db_column='RETURN', max_length=1, null=True)),
                ('DOC_IMAGES', models.CharField(blank=True, db_column='DOC_IMAGES', max_length=50, null=True)),
                ('VERIFIED', models.CharField(blank=True, db_column='VERIFIED', default='V', max_length=1, null=True)),
                ('ORIGINAL', models.CharField(blank=True, db_column='ORIGINAL', max_length=1, null=True)),
                ('PHOTOCOPY', models.CharField(blank=True, db_column='PHOTOCOPY', max_length=1, null=True)),
                ('REMARKS', models.CharField(blank=True, db_column='REMARKS', max_length=500, null=True)),
                ('DEFICIENCY', models.CharField(blank=True, db_column='DEFICIENCY', max_length=1, null=True)),
                ('DOCUMENT_ID', models.ForeignKey(blank=True, db_column='DOCUMENT_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DOCUMENTS_BY_ID', to='student.check_list_documents')),
                ('DOC_NAME', models.ForeignKey(blank=True, db_column='DOC_NAME', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DOCUMENTS_BY_NAME', to='student.check_list_documents', to_field='NAME')),
                ('STUDENT_ID', models.ForeignKey(blank=True, db_column='STUDENT_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DOCUMENTS_BY_STUDENT', to='student.student_master', to_field='STUDENT_ID')),
            ],
            options={
                'verbose_name': 'Student Documents',
                'verbose_name_plural': 'Student Documents',
                'db_table': '"STUDENT"."STUDENT_DOCUMENTS"',
            },
        ),
    ]
