# Generated by Django 5.1.6 on 2025-04-12 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_student_academic_record'),
        ('student', '0012_alter_student_documents_unique_together'),
    ]

    operations = [
    ]
