# Generated by Django 5.1.6 on 2025-04-14 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_merge_20250412_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='STUDENT_ID',
            field=models.ForeignKey(db_column='STUDENT_ID', on_delete=django.db.models.deletion.CASCADE, to='student.student_master', to_field='STUDENT_ID'),
        ),
    ]
