# Generated by Django 5.1.6 on 2025-04-14 09:08

import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_merge_20250414_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_list_documents',
            name='NAME',
            field=models.CharField(db_column='NAME', max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student_documents',
            name='DOC_IMAGES',
            field=models.FileField(blank=True, db_column='DOC_IMAGES', null=True, upload_to=student.models.student_document_upload_path),
        ),
    ]
