# Generated by Django 5.1.6 on 2025-04-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_check_list_documents_name_and_more'),
        ('student', '0014_alter_student_details_student_id'),
    ]

    operations = [
    ]
