# Generated by Django 5.1.6 on 2025-04-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_merge_20250421_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_documents',
            name='RETURN',
            field=models.CharField(blank=True, db_column='RETURN', default='N', max_length=1, null=True),
        ),
    ]
