# Generated by Django 5.1.6 on 2025-05-05 08:16

import academic.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_alter_student_documents_return'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='student_roll_number_details',
        #     name='STUDENT',
        # ),
        # migrations.AddField(
        #     model_name='student_roll_number_details',
        #     name='STUDENT_ID',
        #     field=models.ForeignKey(blank=True, db_column='STUDENT_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roll_number_details', to='student.student_master', to_field='STUDENT_ID'),
        # ),
        migrations.AlterField(
            model_name='student_roll_number_details',
            name='ACADEMIC_YEAR',
            field=models.CharField(db_column='ACADEMIC_YEAR', max_length=10, verbose_name=academic.models.ACADEMIC_YEAR),
        ),
    ]
