# Generated by Django 5.1.6 on 2025-05-05 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_remove_student_roll_number_details_student_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='STUDENT_ROLL_NUMBER_DETAILS',
        ),
    ]
