# Generated by Django 5.1.6 on 2025-05-05 08:36

import academic.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_delete_check_list_documents'),
        ('student', '0018_delete_student_roll_number_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='STUDENT_ROLL_NUMBER_DETAILS',
            fields=[
                ('CREATED_BY', models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_BY', models.CharField(blank=True, db_column='UPDATED_BY', max_length=50, null=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('DELETED_BY', models.CharField(blank=True, db_column='DELETED_BY', max_length=50, null=True)),
                ('DELETED_AT', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('RECORD_ID', models.AutoField(db_column='RECORD_ID', primary_key=True, serialize=False)),
                ('ACADEMIC_YEAR', models.CharField(db_column='ACADEMIC_YEAR', max_length=10, verbose_name=academic.models.ACADEMIC_YEAR)),
                ('ROLL_NO', models.CharField(db_column='ROLLNO', max_length=20)),
                ('BRANCH', models.ForeignKey(db_column='BRANCH_ID', on_delete=django.db.models.deletion.PROTECT, to='accounts.branch')),
                ('INSTITUTE', models.ForeignKey(db_column='INSTITUTE_ID', on_delete=django.db.models.deletion.PROTECT, to='accounts.institute')),
                ('SEMESTER', models.ForeignKey(db_column='SEMESTER_ID', on_delete=django.db.models.deletion.PROTECT, to='accounts.semester')),
                ('STUDENT_ID', models.ForeignKey(blank=True, db_column='STUDENT_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roll_number_details', to='student.student_master', to_field='STUDENT_ID')),
                ('YEAR', models.ForeignKey(db_column='YEAR_ID', on_delete=django.db.models.deletion.PROTECT, to='accounts.year')),
            ],
            options={
                'verbose_name': 'Student Roll Number Details',
                'verbose_name_plural': 'Student Roll Number Details',
                'db_table': '"STUDENT"."STUDENT_ROLL_NUMBER_DETAILS"',
            },
        ),
    ]
